version: "3.0"

networks:
  ms-demo:

services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    restart: on-failure
    expose: 
      - 5672
    ports: 
      - 15672:15672 # Management UI
      - 5672:5672 #AMQP
    volumes:
      - ./.rabbitmq/etc:/etc/rabbitmq/
      - ./.rabbitmq/data:/var/lib/rabbitmq/
      - ./.rabbitmq/logs:/var/log/rabbitmq/
    networks:
      - ms-demo
  
  api_gateway:
    hostname: api_gateway
    container_name: api_gateway
    build:
      context: ./services/api
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - AMQP_USERNAME=admin
      - AMQP_PASSWORD=admin
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
    depends_on:
    - rabbitmq
    networks:
      - ms-demo
