version: "3.0"

networks:
  ms-demo:

services:
  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:3.8-management-alpine
    restart: on-failure
    expose: 
      - 5672
    ports: 
      - 15672:15672 # Management UI
      - 5672:5672 #AMQP
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./.rabbitmq/etc:/etc/rabbitmq/
      - ./.rabbitmq/data:/var/lib/rabbitmq/
      - ./.rabbitmq/logs:/var/log/rabbitmq/
    networks:
      - ms-demo
  
  api_gateway:
    hostname: api_gateway
    container_name: api_gateway
    build:
      context: ./services/api
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - PORT=8000
      - AMQP_CONNECTION_STRING=amqp://admin:admin@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ms-demo

  users:
    hostname: users
    container_name: users
    build:
      context: ./services/users
    restart: on-failure
    environment:
      - AMQP_CONNECTION_STRING=amqp://admin:admin@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - ms-demo
